### PR TITLE
Allow cpu to suspend 

### PR DESCRIPTION
**Pull request by infixremix**
this will getter better idle battery life and removed other msm shit

### CODE REVIEW

**Comment by SphericalKat** [comment]
Are you sure **no other** kernel has this? And that **no one** has implemented these features before? Because you gotta give authorship otherwise.

**Comment by infixremix** [comment]
Every kernel has it , you don't give authorship to defconfig edits , if I was to add CPU suspend then yes but its already implemented in the kernel !

**Comment by infixremix** [comment]
No one owns CPU suspend , kernel.org do no one created it its included in the kernel

**Comment by SphericalKat** [comment]
K sur I'm total noob sur

**Comment by infixremix** [comment]
Na sir , but removing other than 37 configs is just common sense

**Pull request closed without merging**
